baseURL = "https://rex-less.github.io/online-resume/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Rex's Online Resume"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
